version: "2"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./mounts/conf/nginx/proxy/nginx.conf:/etc/nginx/nginx.conf
      - /tmp/nginx:/etc/nginx/conf.d
    hostname: nginx-proxy
    container_name: dev_nginxproxy

  dockergen:
    image: jwilder/docker-gen:latest
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - ./mounts/conf/nginx/templates:/etc/docker-gen/templates
    volumes_from:
      - nginx
    tty: true
    hostname: dockergen
    container_name: dev_dockergen
    command: >
      -watch
      -only-exposed
      -notify-sighup dockerdev_nginx_1
      /etc/docker-gen/templates/nginx.tmpl
      /etc/nginx/conf.d/default.conf
  db:
    image : mariadb:10.1.11
    volumes :
      - mysql-data:/var/lib/mysql
      - ./mounts/conf/mysql/conf.d:/etc/mysql/conf.d
    ports :
      - "3306:3306"
    env_file: mysql.env
    hostname: db
    container_name: dev_mysql

  php:
    image : 4alldigital/drupaldev-php7:latest
    ports :
     - "8022:22"
    volumes :
      - $APPS_PATH/:/docker
      - ./mounts/conf/php7-fpm/cli-php.ini:/etc/php/7.0/cli/php.ini
      - ./mounts/conf/php7-fpm/php.ini:/etc/php/7.0/fpm/php.ini
      - ./mounts/conf/php7-fpm/pool.d/www.conf:/etc/php/7.0/fpm/pool.d/www.conf
    dns:
      - 8.8.8.8
      - 8.8.4.4
    tty : true
    hostname: php
    container_name: dev_php

  mailcatcher:
    image : schickling/mailcatcher
    ports :
      - "1080:1080"
    hostname: mailcatcher
    container_name: dev_mailcatcher

  nginx:
    image : 4alldigital/drupaldev-nginx:latest
    ports :
      - "8088:80"
      - "4443:443"
    volumes :
      - $APPS_PATH:/docker
      - ./mounts/conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./mounts/conf/nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./mounts/conf/nginx/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
      - ./mounts/logs/supervisor:/var/log/supervisor
    env_file: nginx.env
    dns:
      - 8.8.8.8
      - 8.8.4.4
    hostname: nginx
    container_name: dev_nginx

  solr:
    image : 4alldigital/drupaldev-solr:latest
    ports :
      - "8983:8983"
    volumes :
      - ./mounts/conf/solr:/opt/solr/example/solr
    hostname: solr
    container_name: dev_solr

  redis:
    image : 4alldigital/drupaldev-redis:latest
    ports :
      - "6379:6379"
    volumes :
      - ./mounts/conf/redis/redis.conf:/etc/redis/redis.conf
      - ./mounts/conf/redis/sentinel.conf:/etc/redis/sentinel.conf
    hostname: redis
    container_name: dev_redis
    mem_limit: 100000000
    memswap_limit: 2000000000

  behat:
    image: 4alldigital/drupaldev-behat
    volumes:
      - ./mounts/conf/behat/alias.php:/root/.drush/docker.aliases.drushrc.php
      - $APPS_PATH/:/docker
      - $APPS_PATH/tests/screenshots/:/var/tmp/screenshots
      - $APPS_PATH/tests/tmp/:/tmp
    environment:
      website: http://drupal.docker
    hostname: behat
    container_name: dev_behat

  selenium:
    image: selenium/hub
    ports:
      - 4444:4444
    environment :
      - SE_OPTS=-debug
    hostname: selenium
    container_name: dev_selenium

  firefox:
    image: selenium/node-firefox-debug
    ports:
      - 5900
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium
      - HUB_PORT_4444_TCP_PORT=4444
      - no_proxy=localhost
      - REMOTE_HOST_PARAM=-maxSession 4 -browser browserName=firefox,maxInstances=4
    hostname: firefox
    container_name: dev_firefox

  chrome:
    image: selenium/node-chrome-debug
    ports:
      - 5901
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium
      - HUB_PORT_4444_TCP_PORT=4444
      - no_proxy=localhost
      - REMOTE_HOST_PARAM=-maxSession 4 -browser browserName=firefox,maxInstances=4
    hostname: chrome
    container_name: dev_chrome

volumes:
  mysql-data:
    driver: local
