version: "2"
services:
  nginx-proxy:
    volumes:
      - ./mounts/conf/nginx/certs/:/etc/nginx/certs/
  nginx:
    volumes :
      - ./mounts/conf/nginx/certs/:/etc/nginx/certs/
  redis:
    mem_limit: 200000000
    memswap_limit: 4000000000
