version: "2"
#
# [ services definitions ]
#
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./mounts/conf/nginx/proxy/nginx.conf:/etc/nginx/nginx.conf
      - /tmp/nginx:/etc/nginx/conf.d
    hostname: nginx-proxy
    container_name: dev_nginxproxy
    networks:
      - frontend
      - backend

  dockergen:
    image: jwilder/docker-gen:latest
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - ./mounts/conf/nginx/templates:/etc/docker-gen/templates
    volumes_from:
      - nginx
    hostname: dockergen
    container_name: dev_dockergen
    command: >
      -watch
      -only-exposed
      -notify-sighup dockerdev_nginx_1
      /etc/docker-gen/templates/nginx.tmpl
      /etc/nginx/conf.d/default.conf
    networks:
      - frontend

  db:
    image : mariadb:10.1.11
    volumes :
      - mysql-data:/var/lib/mysql
      - ./mounts/conf/mysql/conf.d:/etc/mysql/conf.d
    env_file: mysql.env
    hostname: db
    container_name: dev_mysql
    networks:
      - backend

  php:
    image : 4alldigital/drupaldev-php7:1.0.2
    # ports :
    # - "8022:22"
    volumes :
      - $APPS_PATH/:/docker
      - ./mounts/conf/php7-fpm/cli-php.ini:/etc/php/7.0/cli/php.ini
      - ./mounts/conf/php7-fpm/php.ini:/etc/php/7.0/fpm/php.ini
      - ./mounts/conf/php7-fpm/pool.d/www.conf:/etc/php/7.0/fpm/pool.d/www.conf
    dns:
      - 8.8.8.8
      - 8.8.4.4
    tty : true
    hostname: php
    container_name: dev_php
    networks:
      - backend

  nginx:
    image : 4alldigital/drupaldev-nginx:1.0.2
    volumes :
      - $APPS_PATH:/docker
      - ./mounts/conf/nginx/nginx.conf:/etc/nginx/conf/nginx.conf
      - ./mounts/conf/nginx/pagespeed.conf:/etc/nginx/conf.d/pagespeed.conf
      - ./mounts/conf/nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./mounts/conf/nginx/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    env_file: nginx.env
    hostname: nginx
    container_name: dev_nginx
    networks:
      - backend

  mailcatcher:
    image : schickling/mailcatcher
    hostname: mailcatcher
    container_name: dev_mailcatcher
    networks:
      - backend

  solr:
    image : 4alldigital/drupaldev-solr:1.0.2
    volumes :
      - ./mounts/conf/solr:/opt/solr/example/solr
    hostname: solr
    container_name: dev_solr
    networks:
      - backend

  redis:
    image : 4alldigital/drupaldev-redis:1.0.2
    volumes :
      - ./mounts/conf/redis/redis.conf:/etc/redis/redis.conf
      - ./mounts/conf/redis/sentinel.conf:/etc/redis/sentinel.conf
    hostname: redis
    container_name: dev_redis
    mem_limit: 100000000
    memswap_limit: 2000000000
    networks:
      - backend

  behat:
    image: 4alldigital/drupaldev-behat:1.0.2
    volumes:
      - ./mounts/conf/behat/alias.php:/root/.drush/docker.aliases.drushrc.php
      - $APPS_PATH/:/docker
      - $APPS_PATH/tests/screenshots/:/var/tmp/screenshots
      - $APPS_PATH/tests/tmp/:/tmp
    environment:
      website: http://drupal.docker
    hostname: behat
    container_name: dev_behat
    networks:
      - backend

  selenium:
    image: selenium/hub
    ports:
      - 4444:4444
    environment :
      - SE_OPTS=-debug
    hostname: selenium
    container_name: dev_selenium
    networks:
      - backend

  firefox:
    image: selenium/node-firefox-debug
    ports:
      - 5900
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium
      - HUB_PORT_4444_TCP_PORT=4444
      - no_proxy=localhost
      - REMOTE_HOST_PARAM=-maxSession 4 -browser browserName=firefox,maxInstances=4
    hostname: firefox
    container_name: dev_firefox
    networks:
      - backend

  chrome:
    image: selenium/node-chrome-debug
    ports:
      - 5901
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium
      - HUB_PORT_4444_TCP_PORT=4444
      - no_proxy=localhost
      - REMOTE_HOST_PARAM=-maxSession 4 -browser browserName=firefox,maxInstances=4
    hostname: chrome
    container_name: dev_chrome
    networks:
      - backend

#
# [ volumes definition ]
#
volumes:
  mysql-data:
    driver: local

#
# [ networks definition ]
#
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
